# Generated by Django 5.1.4 on 2024-12-24 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activitytitle', models.CharField(max_length=50)),
                ('activitycoverimage', models.TextField()),
                ('activitycontent', models.TextField()),
                ('activitypublish_time', models.DateTimeField(auto_now_add=True)),
                ('activitystart_time', models.DateTimeField()),
                ('activityend_time', models.DateTimeField()),
                ('activityorganizer', models.CharField(max_length=50)),
                ('activitycontract', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articletitle', models.CharField(max_length=50)),
                ('articletags', models.TextField()),
                ('articlecoverimage', models.TextField()),
                ('articlesummary', models.TextField()),
                ('articlecreated_time', models.DateTimeField(auto_now_add=True)),
                ('articlestatus', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topictitle', models.CharField(max_length=50)),
                ('topictags', models.TextField()),
                ('topicdescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articletype', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('order', models.IntegerField()),
                ('articleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acg.article')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=20)),
                ('avatar', models.TextField(blank=True, default='avatars/avatar.jpg')),
                ('description', models.TextField(blank=True)),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posttitle', models.CharField(max_length=50)),
                ('postcontent', models.TextField()),
                ('postimages', models.TextField()),
                ('posttags', models.TextField()),
                ('postcreated_time', models.DateTimeField(auto_now_add=True)),
                ('authorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acg.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('system', '系统消息'), ('activity', '活动消息'), ('comment', '评论消息'), ('like', '点赞消息')], max_length=10)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='acg.userprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='acg.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenttype', models.CharField(max_length=10)),
                ('commentcontent', models.TextField()),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('articleid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acg.article')),
                ('commentid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acg.comment')),
                ('postid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acg.post')),
                ('commentauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acg.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='authorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acg.userprofile'),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('follower', 'followed')},
            },
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_time', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acg.post')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acg.userprofile')),
            ],
            options={
                'unique_together': {('liker', 'post')},
            },
        ),
        migrations.CreateModel(
            name='LikeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acg.comment')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acg.userprofile')),
            ],
            options={
                'unique_together': {('liker', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='LikeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_time', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acg.article')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acg.userprofile')),
            ],
            options={
                'unique_together': {('liker', 'article')},
            },
        ),
        migrations.CreateModel(
            name='CollectPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_time', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acg.post')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acg.userprofile')),
            ],
            options={
                'unique_together': {('collector', 'post')},
            },
        ),
        migrations.CreateModel(
            name='CollectArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_time', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acg.article')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acg.userprofile')),
            ],
            options={
                'unique_together': {('collector', 'article')},
            },
        ),
    ]
